### PR TITLE
sorted list for better search.

### PR DESCRIPTION
**Pull request by antiDigest**

### CODE REVIEW

**Comment by sara-02** [comment]
@evamy This is good.
 If we replace the digits in the first few names by their corresponding spellings then it should be better sorted, give it a try. Or should we let it be?

**Comment by antiDigest** [comment]
Why do you want its digits replaced with names ?

**Comment by sara-02** [comment]
@evamy Right now the titles starting with numbers are getting sorted at the top that is why.

**Comment by antiDigest** [comment]
Write a simple python/C++/Java code to replace numbers with words and sort ?

**Comment by sara-02** [comment]
Precisely what I intend to do. Python preferred :P
Also, replace numbers that are occurring at the start of the name, otherwise it is just fine.

**Comment by sara-02** [comment]
Closing this as it is duplicate and minor version of #6

**Pull request closed without merging**
